boardgame/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('users/', include('users.urls')),
    path("", include("boardgames.urls")),
]

boardgames/urls.py
from django.urls import path
from . import views

app_name = 'boardgames'
urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    # Page that shows all the games
    path('all_games/', views.all_games, name='all_games'),
    # Page for adding a new boardgame
    path('new_game/', views.new_game, name='new_game'),
    # Detail page for a single boardgame
    path('all_games/<int:game_id>/', views.game_detail, name='game_detail'),
    # Page for editing a board game
    path('edit_game/<int:game_id>/', views.edit_game, name="edit_game"),
    # Page for editing a board game
    path('delete_game/<int:game_id>/', views.delete_game, name="delete_game"),
    # Page for showing user's profile
    path('profile/', views.profile, name='profile'),
    # Page for borrowing a boardgame

    path('borrow_game/<int:game_id>/', views.borrow_game, name='borrow_game'),

    path('return_game/<int:loan_id>/', views.return_game, name='return_game'),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

boardgames/models.py
from django.db import models
from django.contrib.auth.models import User


class BoardGame(models.Model):
    name = models.CharField(max_length=255)
    age_range = models.CharField(blank=True, null=True, max_length= 200)
    description = models.TextField()

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    status_choices = [
        (True, 'Available'),
        (False, 'Borrowed'),
    ]
    is_available = models.BooleanField('Is Available', choices=status_choices, default=True)

    # date and time of creation - required in the task
    date_created = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    # date and time of modification- required in the task
    date_modified = models.DateTimeField(auto_now=True, blank=True)

    class Meta:
        ordering = ['-is_available','-date_modified', '-date_created']

    def __str__(self):
        return self.name


class Loan(models.Model):
    borrower = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    game = models.ForeignKey(BoardGame, on_delete=models.CASCADE)

    borrow_date = models.DateTimeField(auto_now_add=True)

    return_date = models.DateTimeField(blank=True, null=True)
    # is retruned is added so that it is easier to do the query
    is_returned = models.BooleanField('Is returned', default = False)

    def __str__(self):
        # In case it is available
        if self.game.is_available:
            return (f"{self.game.name} is available")
        else: # If it's not available, then give 
            return (f"{self.game.name} is borrowed by {self.borrower.username} on {self.borrow_date}")

boardgames/forms.py
from django import forms
from .models import BoardGame, Loan


class BoardGameForm(forms.ModelForm):
    class Meta:
        model = BoardGame
        fields = ['name', 'age_range', 'description']


class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = []

boardgames/views.py
#from datetime import timezone
from datetime import datetime
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .forms import BoardGameForm, LoanForm
from .models import BoardGame, Loan

def index(request):
    return render(request, 'boardgames/index.html')


def all_games(request):
    """Show all board games."""
    games = BoardGame.objects.all()
    borrowed_games = []
    # if the user is authenticated then do not show the game that is borrowed by him/her
    if request.user.is_authenticated:
        loans = Loan.objects.filter(Q(borrower=request.user) & Q(is_returned = False))
        borrowed_games = [loan.game for loan in loans]

    context = {'games': games, 'borrowed_games': borrowed_games}
    return render(request, 'boardgames/all_games.html', context)


def game_detail(request, game_id):
    """Show information of a boardgame."""
    game = BoardGame.objects.get(id=game_id)
    current_loan = None
    if not game.is_available:
        loan = Loan.objects.filter(Q(game = game) & Q(is_returned = False))
        current_loan = loan[0]
        print(current_loan.borrow_date)
  
    context = {'game': game, "current_loan": current_loan}
    return render(request, 'boardgames/game_detail.html', context)

@login_required
def edit_game(request, game_id):
    """Edit an existing boardgame."""
    game = BoardGame.objects.get(id=game_id)
    # Making sure the game belongs to the current user:
    if game.owner != request.user:
        return HttpResponse("Sorry, only the owner can edit this game")
    if request.method != 'POST':
        # Initial request, pre-fill form with the current experience.
        form = BoardGameForm(instance=game)
    else:
        # POST data submitted -> process the data.
        form = BoardGameForm(instance=game, data=request.POST)
        if form.is_valid():
            form.save()
            # Owner information is already stored.
            # edit_game.owner = request.user
            # edit_game.save()
            return redirect('boardgames:game_detail', game_id=game.id)
    context = {'game': game, 'form': form}
    return render(request, 'boardgames/edit_game.html', context)

@login_required
def delete_game(request, game_id):
    """Delete an existing boardgame."""
    game = BoardGame.objects.get(id=game_id)
    # Making sure the game belongs to the current user:
    if game.owner != request.user:
        return HttpResponse("Sorry, only the owner can delete this game")
    else:
        game.delete()
    return redirect('boardgames:all_games')


@login_required
def new_game(request):
    """Add a new game."""
    if request.method != 'POST':
        # No data submitted -> create a blank form.
        form = BoardGameForm()
    else:
        # Post data submitted -> process the data.
        form = BoardGameForm(data=request.POST)
        
        if form.is_valid():
            new_game = form.save(commit=False)  # Save topic in a variable.
            new_game.owner = request.user  # Set topics owner attribute to current user.
            new_game.save()  # Save the changes to the database.
            return redirect('boardgames:all_games')
    # Display a blank or an invalid form:
    context = {'form': form}
    return render(request, 'boardgames/new_game.html', context)

@login_required
def profile(request):
    """Show information on user's owned boardgames and their loans."""
    games = BoardGame.objects.filter(owner=request.user).all()
    loans = Loan.objects.filter(Q(borrower=request.user) & Q(is_returned = False))
    
    context = {'games': games,'loans': loans}
    return render(request, 'boardgames/profile.html', context)

@login_required
def borrow_game(request, game_id):
    """This function let user borrow new game if they are not currently borrow 3 games."""
    number_of_loans = Loan.objects.filter(Q(borrower = request.user) & Q(is_returned = False))
    game = BoardGame.objects.get(id = game_id)
    # If they have already 3 games in their loans, then show the message.
    if len(number_of_loans) >= 3:
        return HttpResponse("Sorry, you cannot borrow more than 3 games. Please return one and retry again")
    
    if request.method != 'POST':
        form = LoanForm()
    else:
        form = LoanForm(data = request.POST)
        game_form = BoardGameForm(instance=game)
        if form.is_valid():
            # Once user submit the valid loan form, game and borrower will be added to the form.
            new_entry = form.save(commit = False)
            new_entry.game = game
            new_entry.borrower = request.user
            new_entry.save()
            # Change the availability status to False, show that other people can not borrow it.
            game_form2 = game_form.save(commit=False)
            game_form2.is_available = False
            game_form2.save()
            print(game.is_available)
            return redirect('boardgames:profile')
    context = {"form": form, 'game': game}
    return render(request, 'boardgames/borrow_form.html', context)
    
@login_required
def return_game(request, loan_id):
    loan = Loan.objects.get(id=loan_id)
    game = BoardGame.objects.get(id = loan.game.id)
    if request.method != 'POST':
        form = LoanForm()
    else:
        #update is_returned in Loan
        form = LoanForm(instance=loan)
        new_entry = form.save(commit = False)
        new_entry.return_date = datetime.now()
        new_entry.is_returned=True
        new_entry.save()
        #Update is_available in BoardGame
        game_form = BoardGameForm(instance=game)
        game_form2 = game_form.save(commit=False)
        game_form2.is_available = True
        game_form2.save()
        return redirect('boardgames:profile')

    context = {"form": form, 'game': game, 'loan': loan}
    return render(request, 'boardgames/return_form.html', context)

boardgames/templates/boardgames/all_games.html
{% extends "boardgames/base.html" %}

{% block content %}
<h4>All Boardgames</h4>
<br>
<div class="row row-cols-1 row-cols-md-4 g-4" >

    {% for game in games %}
        {% if request.user != game.owner and game not in borrowed_games%}
              <div class="col">
                <div class="card h-80" >
                  <img src="https://img.freepik.com/premium-vector/board-game-themed-seamless-pattern-colorful-cartoon-game-pieces-playing-cards_126267-8260.jpg?w=2000"
                       class="card-img-top" alt="boardgame" style="height: 12rem" />
                  <div class="card-body">
                    <h5 class="card-title" ><a href="{% url 'boardgames:game_detail' game.id %}">{{game}}</a></h5>
                    <p class="card-text">{{game.description}}</p>
                     {% if user == game.owner %}
                    <!-- If the user is not the game owner, then hide the edit and delete function -->
                        <a href="{% url 'boardgames:edit_game' game.id %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'boardgames:delete_game' game.id %}" class="btn btn-primary">Delete</a>

                    <!-- If the user is not the game owner and the game is available, they can borrow -->
                    {% elif game.is_available %}
                        {% if request.user.is_authenticated %}
                        <a href="{% url 'boardgames:borrow_game' game.id %}" class="btn btn-primary">Borrow</a>
                        {% else %} 
                        <a href="{% url 'users:login' %}" class="btn btn-primary">Login to borrow</a>
                        {% endif %}
                    <!-- If the game is not available, then tell the user who borrowed it and when -->
                    {% elif not game.is_available %}
                      <p>This game is unavailable at the moment </p>

                    {% endif %}
                  </div>
                </div>
              </div>

        {% endif %}
        {% empty %}
            <li>No boardgame have been added yet.</li>
        
    {% endfor %}
</div>
{% if user.is_authenticated %}
    <a href="{% url 'boardgames:new_game' %}" >Add a new boardgame</a>
{% endif %}

{% endblock content %}

boardgames/templates/boardgames/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Board Game Club</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

  </head>
  <body>
  <header>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
          <a class="navbar-brand" href="{% url 'boardgames:index' %}">Board Game Club</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
          aria-controls="navbarCollapse" aria-expanded="false" aria-label="Togglenavigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'boardgames:all_games' %}">All Games</a></li>
              </ul>
              <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                  <li class="nav-item">
                    <span class="navbar-text">Hello, <a href="{% url 'boardgames:profile' %}">{{ user.username }}.</a></span>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                  </li>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                  </li>
                {% endif %}
              </ul>
          </div>
        </nav>

  </header>
{% block content %}

{% endblock content %}

boardgames/templates/boardgames/borrow_form.html
{% extends "boardgames/base.html" %}
<h4>Borrow</h4>

{% block content %}
  <p>Are you sure you want to borrow {{ game }}</p>
  <form action="{% url 'boardgames:borrow_game' game.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
      <button name="submit" class="btn btn-primary" >Yes, borrow!</button>
  </form>
{% endblock content %}

boardgames/templates/boardgames/edit_game.html
{% extends "boardgames/base.html" %}
<h4>Board Game: {{ game }}</h4>

{% block content %}
  <p>Edit Boardgame:</p>
  <form action="{% url 'boardgames:edit_game' game.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
      <button name="submit" >Save changes</button>
  </form>
{% endblock content %}

boardgames/templates/boardgames/game_detail.html
{% extends "boardgames/base.html" %}

{% block content %}

    <h1>About {{ game }}</h1>
    <p>Name: {{ game.name }}</p>
    <p>Age range: {{ game.age_range }}</p>
    <p>Description: {{ game.description }}</p>
    <p> Owned by {{game.owner}}</p>

    {% if user == game.owner %}
    <!-- If the user is not the game owner, then hide the edit and delete function -->
        <a href="{% url 'boardgames:edit_game' game.id %}" class="btn btn-primary">Edit</a>
        <a href="{% url 'boardgames:delete_game' game.id %}" class="btn btn-primary">Delete</a>

    <!-- If the user is not the game owner and the game is available, they can borrow -->
    {% elif game.is_available %}
        {% if request.user.is_authenticated %}
        <a href="{% url 'boardgames:borrow_game' game.id %}" class="btn btn-primary">Borrow</a>
        {% else %} 
        <a href="{% url 'users:login' %}" class="btn btn-primary">Login to borrow</a>
        {% endif %}
        
    <!-- If the game is not available, then tell the user who borrowed it and when -->
    {% elif not game.is_available %}
        <p>Game is borrowed by <strong>{{current_loan.borrower}}</strong> on {{current_loan.borrow_date}}</p>
        
    {% endif %}

{% endblock content %}

boardgames/templates/boardgames/index.html
{% extends 'boardgames/base.html' %}
{% load bootstrap4 %}

{% block content %}
 <!-- Background image -->
  <div class="p-5 text-center bg-image" style="
      background-image: url('https://img.freepik.com/premium-vector/hand-drawn-seamless-pattern-board-game-element_253081-414.jpg?w=2000');
      height: 500px;
      margin-top: 100px;
    ">
    <div class="mask" style="width:100%; height:100%; position:relative; left:0;top:0;overflow:hidden; background-color: rgba(0, 0, 0, 0.7); ">
      <div class="d-flex justify-content-center align-items-center h-100">
        <div class="text-white">
          <h1 class="mb-3">Welcome to Board Game Club!</h1>
          <h4 class="mb-3">Lend and borrow your favorite boardgame with a click away!</h4>
          <a class="btn btn-outline-light btn-lg m-2" href="{% url 'users:register' %}"
            role="button" rel="nofollow" target="_blank">Register</a>
          <a class="btn btn-outline-light btn-lg m-2" href="{% url 'users:login' %}"
            target="_blank" role="button">Login</a>
        </div>
      </div>
    </div>
  </div>
  <!-- Background image -->
{% endblock %}

boardgames/templates/boardgames/new_game.html
{% extends "boardgames/base.html" %}
{% block page_header %}
  <h2>Add a new boardgame</h2>
{% endblock page_header %}
{% block content %}

<form action="{% url 'boardgames:new_game' %}" method='post' class="form">
    {% csrf_token %}
    {{form.as_p}}
    <button name="submit" class="btn btn-primary">Add a new boardgame</button>
</form>
{% endblock content %}

boardgames/templates/boardgames/profile.html
{% extends 'boardgames/base.html' %}

{% block content %}
<h4>My Boardgames</h4>
<br>
<div class="row row-cols-1 row-cols-md-4 g-4" >

    {% for game in games %}
              <div class="col">
                <div class="card h-100" >
                  <img src="https://img.freepik.com/premium-vector/board-game-themed-seamless-pattern-colorful-cartoon-game-pieces-playing-cards_126267-8260.jpg?w=2000"
                       class="card-img-top" alt="boardgame" style="height: 12rem" />
                  <div class="card-body">
                    <h5 class="card-title" ><a href="{% url 'boardgames:game_detail' game.id %}">{{game}}</a></h5>
                    <p class="card-text">{{game.description}}</p>

                      {% if user == game.owner %}
                        {% if game.current_loan %}
                         <p>Game is borrowed by <strong>{{game.current_loan.borrower}}</strong> on {{game.current_loan.borrow_date}}</p>
                        {% endif %}
                        <a href="{% url 'boardgames:edit_game' game.id %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'boardgames:delete_game' game.id %}" class="btn btn-primary">Delete</a>
                      {% endif %}
                  </div>
                </div>
              </div>

        {% empty %}
            <li>No boardgame have been added yet.</li>

    {% endfor %}
</div>
<br>
<a href="{% url 'boardgames:new_game' %}">Add a new boardgame</a>
<br>
<br>
<h4>My Current Loans</h4>
<div class="row row-cols-1 row-cols-md-4 g-4" >
{% for loan in loans %}
    <div class="col">
        <div class="card h-100" >
            <img src="https://img.freepik.com/premium-vector/board-game-themed-seamless-pattern-colorful-cartoon-game-pieces-playing-cards_126267-8260.jpg?w=2000"
                       class="card-img-top" alt="boardgame" style="height: 12rem" />
            <div class="card-body">
                <h5 class="card-title" ><a href="{% url 'boardgames:game_detail' loan.game.id %}">{{loan.game}}</a></h5>
                <p>Date borrowed: {{loan.borrow_date}}</p>

                <a href="{% url 'boardgames:return_game' loan.id %}" class="btn btn-primary">Return</a>
            </div>
        </div>
    </div>
{% empty %}
    <p style="margin-left: 20px">You have not borrow any games yet</p>
{% endfor %}
</div>

{% endblock content%}

boardgames/templates/boardgames/return_form.html
{% extends "boardgames/base.html" %}
<h4>Borrow</h4>

{% block content %}
  <p>Are you sure you want to return {{ game }}</p>
  <form action="{% url 'boardgames:return_game' loan.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
      <button name="submit" class="btn btn-primary" >Yes, return!</button>
  </form>
{% endblock content %}